export const gbpLocation = {
  storeName: "PLANETS 59",
  domain: "www.planets59.com",
  city: "Brampton",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-brampton",
  address: "8500 Torbram Rd #59, Brampton, ON L6T 5C6",
  streetAddress: "8500 Torbram Rd #59",
  postalCode: "L6T 5C6",
  phone: "(416) 300-7806",
  phoneIntl: "+14163007806",
  neighborhood: "Brampton",
  nearbyAreas: ["Brampton", "Torbram Road", "Steeles Avenue East", "Bramalea", "Peel Region", "Brampton Transit"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "",
  mapEmbedUrl: "https://www.google.com/maps?q=8500%20Torbram%20Rd%20%2359%2C%20Brampton%2C%20ON%20L6T%205C6&output=embed",
  latitude: "43.7258",
  longitude: "-79.6953",
  hours: ["Open Daily: 10:00 AM - 01:00 AM"],
  seoTitle: "PLANETS 59 | Weed Dispensary in Brampton",
  metaDescription: "PLANETS 59 is a local weed dispensary in Brampton offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Torbram Road", "Steeles Avenue East", "Tor Valley Shopping Centre"],
  introVariant: "PLANETS 59 is a local weed dispensary in Brampton, located at 8500 Torbram Rd #59. We serve adults 19+ looking for quality weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, shatter, CBD oils, and accessories. Whether you are searching for a weed dispensary near Brampton, a cannabis store in Brampton, or a local weed shop near Torbram Road and Steeles Avenue East, use the current menu and staff for product details.",
  neighborhoodDescription: "Located near Torbram Road and Steeles Avenue East, the store sits in a practical Brampton plaza area with nearby retail, parking, and transit links.",
  parkingNote: "Plenty of plaza parking is available in the Tor Valley Shopping Centre",
  transitNote: "Served by Brampton Transit routes along Torbram Road and Steeles Avenue.",
  sectionTitle: "Serving Customers Near Brampton and Peel Region"
};
