// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "PLANETS 59",
  domain: "planets59.com",
  city: "Brampton",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-brampton",
  address: "8500 Torbram Rd #59, Brampton, ON L6T 5C6",
  streetAddress: "8500 Torbram Rd #59",
  postalCode: "L6T 5C6",
  phone: "(416) 300-7806",
  phoneIntl: "+14163007806",
  neighborhood: "Brampton",
  nearbyAreas: ["Brampton", "Queen Street", "Main Street", "Downtown Brampton", "Kennedy Road", "Bramalea", "Peel Region", "Brampton Transit"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://maps.google.com/?q=8500+Torbram+Rd+%2359,+Brampton,+ON+L6T+5C6",
  mapEmbedUrl: "https://maps.google.com/maps?q=8500%20Torbram%20Rd%20%2359%2C%20Brampton%2C%20ON%20L6T%205C6&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.7258",
  longitude: "-79.6953",
  hours: ["Open Daily: 10:00 AM - 01:00 AM"],
  seoTitle: "PLANETS 59 | Weed Dispensary in Brampton",
  metaDescription: "PLANETS 59 is a local weed dispensary in Brampton offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["Brampton", "Queen Street", "Main Street"],
  introVariant: "PLANETS 59 is a local weed dispensary in Brampton, located at 8500 Torbram Rd #59. We serve adults 19+ looking for quality weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, shatter, CBD oils, and accessories. Whether you are searching for a weed dispensary near Brampton, a cannabis store in Brampton, or a local weed shop close to Queen Street, our friendly team is here to help you find the right product.",
  neighborhoodDescription: "Located in the vibrant Brampton district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Plenty of plaza parking is available in the Tor Valley Shopping Centre",
  transitNote: "Served by Brampton Transit routes along Torbram Road and Steeles Avenue.",
  sectionTitle: "Serving Customers Near Brampton and Peel Region"
};
